"""m2m insert careerxsubject

Revision ID: 4a5c57c09beb
Revises: 0e7d2011897e
Create Date: 2023-10-10 20:42:29.092254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5c57c09beb'
down_revision: Union[str, None] = '0e7d2011897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('career_subject_association', 'career_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('career_subject_association', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('career_subject_association', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('career_subject_association', 'career_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
